### ISSUE TITLE
Specify container

### ISSUE THREAD

**Issue by chevdor** [manumilou/gitlab-ci-example-asciidoc#1]
Does it work at all as you have it now ?

I would suggest using a docker image that contains all the asciidoctor goodies and enable the unsafe flag.

Here is what I use as `.gitlab-ci-yml`:
```
image: asciidoctor/docker-asciidoctor

pdf:
  script: 
     - asciidoctor-pdf -a pdf-stylesdir=resources -n -a pdf-style=sfl -a allow-uri-read README.adoc
  artifacts:
    paths:
     - README.pdf

html:
  script: 
     - asciidoctor README.adoc
  artifacts:
    paths:
     - README.html
```
